title: Jiajun Zhou
logo: /asset/img/jjc.png
description: The creative spirits. The underdogs. The resolute. The determined. The indefatigable. The outsiders. The defiant. The independent thinkers. The fighters and the true believers.
show_downloads: false
theme: jekyll-theme-minimal
